### ISSUE TITLE
v5.3.0 only runs on files in the root directory

### ISSUE THREAD

**Issue by dongyuzheng** [pre-commit/mirrors-eslint#15] opened 2018-08-15 17:50 UTC
## Behaviour

* expected: runs against all files matching  `\.jsx?$`  recursively
* actual: only runs against files matching pattern in root directory

## `.pre-commit-config.yaml`
```
repos:
  -
    repo: 'git://github.com/pre-commit/pre-commit-hooks'
    rev: v1.4.0
    hooks:
      -
        id: trailing-whitespace
      -
        id: end-of-file-fixer
      -
        id: mixed-line-ending
        args:
          - '--fix=lf'
  # -
  #   repo: 'git://github.com/prettier/prettier'
  #   rev: 1.14.2
  #   hooks:
  #     -
  #       id: prettier
  #       files: '\.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md)$'
  -
    repo: 'git://github.com/pre-commit/mirrors-eslint'
    rev: v4.19.1 #v5.3.0
    hooks:
      -
        id: eslint
        files: '\.jsx?$'
        entry: echo eslint
        verbose: true
        args:
          - '--fix'
        additional_dependencies:
          - eslint
          - eslint-config-airbnb
          - eslint-plugin-import
          - eslint-plugin-jsx-a11y
          - eslint-plugin-react
          - eslint-plugin-css-modules
```
**I added `entry: echo eslint` to print which files were being inputted.**

## v5.3.0 output
```
gary@gary-ubuntu-desktop:~/pg/rezq-frontend (dzheng/fix-eslint)$ .venv/bin/pre-commit run --all-files
[INFO] Initializing environment for git://github.com/pre-commit/mirrors-eslint:eslint,eslint-config-airbnb,eslint-plugin-css-modules,eslint-plugin-import,eslint-plugin-jsx-a11y,eslint-plugin-react.
[INFO] Installing environment for git://github.com/pre-commit/mirrors-eslint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
eslint...................................................................Passed
hookid: eslint

eslint --fix webpack.common.js webpack.dev.js webpack.prod.js
```

## v4.19.1 output
```
gary@gary-ubuntu-desktop:~/pg/rezq-frontend (dzheng/fix-eslint)$ .venv/bin/pre-commit run --all-files
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
eslint...................................................................Passed
hookid: eslint

eslint --fix <all the files>
```

**Comment by asottile** [comment] 2018-08-15 17:52
dupe of #14: See https://github.com/pre-commit/mirrors-eslint/issues/14#issuecomment-409338194

**Closed by asottile** 2018-08-15 17:52 UTC

**Comment by dev-test-gg** [comment] 2019-03-28 17:54
Hi ! 

I'm having the exact same issue. I read your comment on the other issue, but I could not manage to fix it by using 
`   types: [file]
    files: \.jsx?$`

Here's my config:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.12.0 # Use the sha / tag you want to point at
    types: [file]
    files: \.jsx?$
    hooks:
      - id: eslint
        args: [-c, ./front/.eslintrc]
        additional_dependencies:
          - eslint
          - eslint-import-resolver-alias
          - eslint-plugin-import
          - eslint-plugin-jsx-a11y
          - eslint-plugin-prettier
          - eslint-plugin-react
          - eslint-config-react-app
          - eslint-plugin-flowtype
          - babel-eslint
          - eslint-config-prettier
          - prettier

Do you know what I'm doing wrong? 

Thanks

**Comment by Lotram** [comment] 2019-03-28 17:58
Hi, I have exactly the same issue, and could not fix it by using 
`
    types: [file]
    files: \.jsx?$
`
Here is my config:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.12.0 # Use the sha / tag you want to point at
    types: [file]
    files: \.jsx?$
    hooks:
      - id: eslint
        args: [-c, ./front/.eslintrc]
        additional_dependencies:
          - eslint
          - eslint-import-resolver-alias
          - eslint-plugin-import
          - eslint-plugin-jsx-a11y
          - eslint-plugin-prettier
          - eslint-plugin-react
          - eslint-config-react-app
          - eslint-plugin-flowtype
          - babel-eslint
          - eslint-config-prettier
          - prettier

Do you know what I'm doing wrong?

**Comment by asottile** [comment] 2019-03-28 18:03
Looks right to me, what are you seeing?

**Comment by Lotram** [comment] 2019-03-28 19:03
Wow you're fast !

I tried with 2 staged files : 1 in the root directory, another 1 deeper (both containing errors). The first one is parsed, therefore the pre-commit fails, but if I remove it and keep only the second one in staged changes, the hook is passing (not skipped though). If i run the command with --all-files, it fails as expected.

**Comment by asottile** [comment] 2019-03-28 20:36
try setting `verbose: true` for the hook to see what it's doing?

Also maybe try the same setup but with the `identity` hook to see what filenames are being passed along: https://pre-commit.com/#meta-hooks

also double check that your `.eslintrc` isn't excluding files?

**Comment by Lotram** [comment] 2019-03-28 20:54
Ok thanks, i'll try that tomorrow morning.
I'm pretty sure it's not coming from .eslintrc  or eslint, it's working properly when running eslint directly

**Comment by Lotram** [comment] 2019-03-29 09:19
It seems it's actually a problem with eslint conf when using pre-commit.
I put this file in front (notice the multiple line breaks): 
```console.log("hey")


 ```
and the ouput is : 
```
eslint...................................................................Failed
hookid: eslint

~/project/front/heyInFront.js
  2:1  error  Delete `⏎⏎⏎`  prettier/prettier
```
But I'm also using eslint:recommended in my .eslintrc, so the console.log should also raise an error. If I remove the extra lines, it passes

**Comment by asottile** [comment] 2019-03-29 09:21
pre-commit passes all modified filenames as positional arguments

so in your example it'd run `eslint -c ./front/.eslintrc file1.js file2.jsx ...`

**Comment by Lotram** [comment] 2019-03-29 09:46
Ok i know what was the problem: I had unstaged changes in my .eslintrc (eslint:recommended among other things), so of course pre-commit stashed it before running eslint...

I'm new to pre-commit, I should have understood that before.

Anyway thanks a lot for your help, I'll will definitely try setting up pre-commit properly and write my own hooks

**Comment by asottile** [comment] 2019-03-29 10:44
ah! ok :)

heh the full command you ran and the full output it produced would have hinted there -- I guess for next time include that in your message :D

Good to hear you found the cause though 🎉
